unique_ids:
  assets:
    standard-page.html: Q26E3G3DWFI7LVQZTCKHHYZMPM3RQPEB
    theme.css: O4PBLSBJ2O6QKKIGPGUGKZBSF5AFOSYK
  forms:
    Form1: XCS7J5MPDK5RZQAMIACMXZ37EKIQ6FA7
  modules: {}
  scripts: {}
  server_modules: {}
